const express = require('express');       
const router = express.Router();         
const { register, login, me, updateProfile, changePassword, requestReset, resetPassword } = require('../controllers/authController'); 
const authMiddleware = require('../middleware/authMiddleware'); 
router.post('/register', register); 
router.post('/login', login); 
router.get('/me', authMiddleware, me); 
router.patch('/profile', authMiddleware, updateProfile); 
router.patch('/password', authMiddleware, changePassword); 
router.post('/request-reset', requestReset);   
router.post('/reset-password', resetPassword); 
module.exports = router; 